---
sudo: false

language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6

cache: bundler

before_install:
  - gem install bundler --no-document

script:
  - bundle exec rake test
  - bundle exec rubocop

notifications:
  email: false
